# Generated by Django 6.0.7 on 2026-07-11 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_department_code_department_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='building',
            field=models.CharField(default='Main Block', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.department'),
        ),
    ]
